language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
before_script:
  - "echo \"DataTracker::Application.config.secret_token = '$(bundle exec rake secret)'\" > config/initializers/secret_token.rb"
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
