language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3
  - 2.4.0
env:
  - DB=sqlite
  - DB=postgres
  - DB=mysql
before_script:
  - "echo \"LedgrApp::Application.config.secret_token = '$(bundle exec rails secret)'\" > config/initializers/secret_token.rb"
  - "echo \"LedgrApp::Application.config.secret_key_base = '$(bundle exec rails secret)'\" > config/initializers/secret_token.rb"
  - "echo \"Devise.secret_key = '$(bundle exec rails secret)'\" >> config/initializers/secret_token.rb"
  - "echo \"LedgrApp::Application.config.twofactor_key = '$(bundle exec rails secret)'\" >> config/initializers/secret_token.rb"
  - psql -c 'create database ledgr_test' -U postgres
  - mysql -e 'create database ledgr_test;'
  - mysql -e "GRANT ALL PRIVILEGES ON ledgr_test.* TO 'travis'@'%';"
script:
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rails test
