language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - "echo \"DataTracker::Application.config.secret_token = '$(bundle exec rake secret)'\" > config/initializers/secret_token.rb"
  - "echo \"Devise.secret_key = '$(bundle exec rake secret)'\" >> config/initializers/secret_token.rb"
  - psql -c 'create database daytum_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
